sudo: required
services: 
  - docker

before_install: 
  - docker build -t someshjha/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true someshjha/docker-react npm run test -- --coverage

deploy:
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-780994390681"
  bucket_path: "docker-react"
  on: 
    branch: master

language: generic